/*
 * SQL Query - Generated by Data Troubleshooter Agent
 * ================================================
 * Created: 2026-01-13T03:13:26.708Z
 * Platform: other
 * 
 * This file is version-controlled and can be:
 * - Re-executed anytime via right-click context menu
 * - Shared with team via Git
 * - Used in CI/CD pipelines for data testing
 * - Modified and customized as needed
 */

select * from DBT_DB.DBT_SCHEMA.fact_orders limit 20
