/*
 * SQL Query - Generated by Data Troubleshooter Agent
 * ================================================
 * Created: 2026-01-12T23:20:05.490Z
 * Platform: duckdb
 * 
 * This file is version-controlled and can be:
 * - Re-executed anytime via right-click context menu
 * - Shared with team via Git
 * - Used in CI/CD pipelines for data testing
 * - Modified and customized as needed
 */

SELECT 
    ROUND(AVG(ABS(item_discount_amount / extended_price)), 4) AS avg_discount_ratio,
    MIN(order_date) AS min_date,
    MAX(order_date) AS max_date
FROM {{ ref('int_order_items') }}
