/*
 * SQL Query - Generated by Data Troubleshooter Agent
 * ================================================
 * Created: 2026-01-24T17:51:19.780Z
 * Platform: duckdb
 * 
 * This file is version-controlled and can be:
 * - Re-executed anytime via right-click context menu
 * - Shared with team via Git
 * - Used in CI/CD pipelines for data testing
 * - Modified and customized as needed
 */

SELECT * FROM fact_orders LIMIT 10
