/*
 * SQL Query - Generated by Data Troubleshooter Agent
 * ================================================
 * Created: 2026-02-06T20:55:32.028Z
 * Platform: duckdb
 * 
 * This file is version-controlled and can be:
 * - Re-executed anytime via right-click context menu
 * - Shared with team via Git
 * - Used in CI/CD pipelines for data testing
 * - Modified and customized as needed
 */

select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.fact_orders limit 5
