/*
 * SQL Query - Generated by Data Troubleshooter Agent
 * ================================================
 * Created: 2026-01-26T18:26:39.301Z
 * Platform: snowflake
 * 
 * This file is version-controlled and can be:
 * - Re-executed anytime via right-click context menu
 * - Shared with team via Git
 * - Used in CI/CD pipelines for data testing
 * - Modified and customized as needed
 */

SHOW TABLES IN SCHEMA SNOWFLAKE_SAMPLE_DATA.TPCH_SF1
