/*
 * SQL Query - Generated by Data Troubleshooter Agent
 * ================================================
 * Created: 2026-02-27T22:20:36.696Z
 * Platform: snowflake
 * 
 * This file is version-controlled and can be:
 * - Re-executed anytime via right-click context menu
 * - Shared with team via Git
 * - Used in CI/CD pipelines for data testing
 * - Modified and customized as needed
 */

SELECT * FROM fact_orders ORDER BY order_date DESC LIMIT 10
