/*
 * SQL Query - Generated by Data Troubleshooter Agent
 * ================================================
 * Created: 2026-01-26T03:50:29.884Z
 * Platform: snowflake
 * Purpose: Ensure amount is positive
 * 
 * This file is version-controlled and can be:
 * - Re-executed anytime via right-click context menu
 * - Shared with team via Git
 * - Used in CI/CD pipelines for data testing
 * - Modified and customized as needed
 */

SELECT COUNT(*) as negative_values FROM int_order_items_summary WHERE amount < 0
