/*
 * SQL Query - Generated by Data Troubleshooter Agent
 * ================================================
 * Created: 2026-01-26T03:50:16.496Z
 * Platform: snowflake
 * Purpose: Verify stg_tpch_orders table exists
 * 
 * This file is version-controlled and can be:
 * - Re-executed anytime via right-click context menu
 * - Shared with team via Git
 * - Used in CI/CD pipelines for data testing
 * - Modified and customized as needed
 */

SELECT COUNT(*) as table_exists FROM information_schema.tables WHERE table_name = 'stg_tpch_orders'
